### ISSUE TITLE
Convert to Foundation 6 class names and use flexbox

### ISSUE THREAD

**Issue by pennybuster** [RedCastor/bs3-2-zf6#1]
Hi there! Please create a script to convert to Foundation 6 class names and use flexbox.
Thanks a lot!!!

**Comment by auban** [comment]
Hello, can you explain more.

**Comment by pennybuster** [comment]
Hi again. I mean like this: http://upgrade-bootstrap.bootply.com/
What I don't know is if it's possible to replace floats with Flexbox.

**Comment by auban** [comment]
Sorry but this project is a bridge for bootstrap3 and not bootstrap4.

**Comment by pennybuster** [comment]
I included that script as an example. The conversion would be from Bootstrap 3 to Foundation 6.
